function dv_dt = acceleration(gravity, dragCoefficient, mass, velocity)

%acceleration SOLVES FOR THE ACCELERATION OF A GIVEN OBJECT AT A GIVEN TIME
%  THIS FUNCTION SOLVES THE ACCELERATION OF A MASS IN FREE FALL AFFECTED BY 
%   DRAG. THIS FUNCTION TAKES IN FOUR PARAMETERS: gravity, dragCoefficient, mass 
%   WHICH ARE ALL PARAMETERS THAT CAN BE PLAYED WITH FOR OBJECTS OF
%   DIFFERENT MASS WITH DIFFERENT DRAG COEFFICIENTS UNDER THE FORCE OF DIFFERENT
%   GRAVITY, AND velocity WHICH DEFINES THE VELOCITY OF THE OBJECT AT THE TIME
%   ACCELERATION NEEDS TO BE CALCULATED FOR

    g = gravity;            %
    c = dragCoefficient;    % VARIABLE DEFINITIONS THAT MAKE TYPING EASIER
    m = mass;               % 
    v = velocity;           %
    
    % CALCULATE ACCELERATION BASED ON PARAMETERS GIVEN
    dv_dt = g - (c/m) * v^2;
    % dv_dt NOW EQUALS THE ACCELERATION OF THE OBJECT AT VELCOITY velocity

end

